version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: my-app-php
    volumes:
      - ./my-app:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: my-app-nginx
    ports:
      - "8081:81"
    volumes:
      - ./my-app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:5.7
    container_name: my-app-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: myapp
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3310:3306"
    networks:
      - laravel

  queue:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: myapp-queue-worker
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    volumes:
      - ./my-app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - app
      - mysql
    networks:
      - laravel

volumes:
  mysql-data:

networks:
  laravel:
    driver: bridge
